// src/constants/iconConstants.tsx
import {
    UserOutlined,
    MailOutlined,
    LockOutlined,
    HomeOutlined,
    EyeOutlined,
    EditOutlined,
    DeleteOutlined,
    BarChartOutlined,
    IdcardOutlined,
    PhoneOutlined,
    LinkedinOutlined,
    TwitterOutlined,
    GithubOutlined,
    FacebookOutlined,
    InstagramOutlined,
    YoutubeOutlined,
    WhatsAppOutlined,
    LinkOutlined,
    StarOutlined,
    BulbOutlined,
    BookOutlined,
    SearchOutlined,
    DashboardOutlined,
    SettingOutlined,
    NotificationOutlined,
    AuditOutlined,
    CheckCircleOutlined,
    FormOutlined,
    PieChartOutlined,
    QuestionCircleOutlined,
    CheckSquareOutlined
} from "@ant-design/icons";

export const Icons = {
    user: <UserOutlined />,
    mail: <MailOutlined />,
    lock: <LockOutlined />,
    home: <HomeOutlined />,
    view: <EyeOutlined />,
    edit: <EditOutlined />,
    delete: <DeleteOutlined />,
    barChart: <BarChartOutlined />,
    idCard: <IdcardOutlined />,
    phone: <PhoneOutlined />,
    linkedin: <LinkedinOutlined />,
    twitter: <TwitterOutlined />,
    github: <GithubOutlined />,
    facebook: <FacebookOutlined />,
    instagram: <InstagramOutlined />,
    youtube: <YoutubeOutlined />,
    whatsapp: <WhatsAppOutlined />,
    link: <LinkOutlined />,
    star: <StarOutlined />,
    bulb: <BulbOutlined />,
    book: <BookOutlined />,
    search: <SearchOutlined />,
    dashboard: <DashboardOutlined />,
    setting: <SettingOutlined />,
    notification: <NotificationOutlined />,
    audit: <AuditOutlined />,
    checkCircle: <CheckCircleOutlined />,
    form: <FormOutlined />,
    pieChart: <PieChartOutlined />,
    questionCircle: <QuestionCircleOutlined />,
    tickCircle: <CheckSquareOutlined />,
};
