export const STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  EXPIRED: "EXPIRED",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SUSPENDED: "SUSPENDED",
  DELETED: "DELETED",
  BLOCKED: "BLOCKED",
  ARCHIVED: "ARCHIVED",
  ARCHIVED: "ARCHIVED",
});
